export default {
    name: "EulerBeats",
    description: "Ultra scarce digital art + beat collection generated by applying mathematical discoveries of Euler",
    slug: "eulerbeats",
    website: "https://eulerbeats.com/",
    image: {
        thumbnail: "https://assets.fractional.art/media/analysis/eulerbeats_thumbnail.jpg",
        banner: "https://assets.fractional.art/media/analysis/eulerbeats_banner.jpg",
        source: "https://twitter.com/eulerbeats/status/1379779177193295872",
    },
    contracts: [
        {
            address: "0x8754f54074400ce745a7ceddc928fb1b7e985ed6",
            tokenIds: []
        },
        {
            address: "0xa98771a46dcb34b34cdad5355718f8a97c8e603e",
            tokenIds: []
        },
    ],
    analysis: [
        {
            title: "General",
            content: "Created by Treum, Euler Beats is an algorithmically generated NFT project that pairs percussion & rhythmic based audio tracks with unique animated visuals. Both the debut collection <i>Genesis</i> and the follow up <i>Enigma</i> are limited to 27 Original tracks. Notably, owners also receive royalties from secondary sales as well as retain full ownership rights to the track. Sitting at the intersection of art, music, and finance, Euler Beats is one of the most innovative projects to hit the NFT space in recent memory."
        },
        {
            title: "Cultural Significance",
            content: "Euler Beats is the first music project to be stored completely on-chain. Because both the script and the seed of each Original is stored on the Ethereum blockchain, each audio and visual output will be able to be recreated indefinitely without the need for third-party file storage systems. As a result, owners of Originals possess full commercial copyrights for their tracks forever."
        },
        {
            title: "Macro",
            content: "Euler Beats was one of the first projects to effectively incorporate DeFi principles into an NFT project. Owners of Original tracks receive 8% royalties on sales of all Prints in perpetuity. Limited to 120, Prints are replicas that can be minted and burned on a bonding curve. When a collector purchases a print, the amount is credited towards a reserve pool and the price for the ensuing print increases. When selling, the collector receives 90% of the current price which is withdrawn from the reserve, and the price decreases. Crucially, this provides holders of Prints immediate access to liquidity and encourages higher sales volume, which benefits holders of Originals. Euler Beats is a pioneer for audio ownership, distribution models, and the monetization of NFTs."
        },
        {
            title: "Metrics",
            content:"The <i>Genesis</i> series has totaled over $25M in sales, while the <i>Enigma</i> series sits at $6.5M. The most recent sale for any Original track, <i>Enigma LP12</i>, was for 79 ETH in April of 2021. Currently, the lowest priced Genesis Original on the secondary market is listed for 59 ETH, compared to 50 ETH for an Enigma. The projects have sold roughly $108k during the past 30 days."
        },
        {
            title: "Risk",
            content: "Cryptocurrencies are inherently risky, and emerging asset classes like NFTs are no exception towards the rule. Music based NFT projects are still in their infancy and valuations for these assets may take time to settle. While the NFT space has seen strong momentum, that may not always be the case; research accordingly and proceed with caution."
        }
    ],
}
